language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
notifications:
  email: true
node_js:
  - '12'
install:
  - npm install
script:
  - npm run lint
  - npm run cy:run
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
